name: add_it
description: A new Flutter project.

dependencies:
  #flutter:
  #  sdk: flutter
  flutter_web: any
  flutter_web_ui: any
  rxdart: ^0.18.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  build_runner: any
  build_web_compilers: any

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui